name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Load .env file
      run: |
        echo "HEROKU_API_KEY=$(grep HEROKU_API_KEY .env | cut -d '=' -f2)" >> $GITHUB_ENV

    - name: Create Heroku app if it doesn't exist
      env:
        HEROKU_API_KEY: ${{ env.HEROKU_API_KEY }}
      run: |
        heroku apps:create clasificador_vinos || echo "App already exists"

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ env.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a clasificador_vinos
        git push heroku main

