name: Deploy to Heroku

on:
  push:
    branches:
      - streamlit

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Load .env file
      run: |
        echo "HEROKU_API_KEY=$(grep HEROKU_API_KEY .env | cut -d '=' -f2)" >> $GITHUB_ENV

    - name: Ensure Heroku app exists
      env:
        HEROKU_API_KEY: ${{ env.HEROKU_API_KEY }}
      run: |
        if ! heroku apps:info -a clasificadorvino; then
          heroku apps:create clasificadorvino
        fi

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ env.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a clasificadorvino
        git push heroku streamlit:main
